In [6]:
import pandas as pd

In [7]:
samples = ["DMSO-Total-1", "DMSO-Total-2", "DMSO-Total-3", "TPG-Total-1", "TPG-Total-2", "TPG-Total-3",
                    "DMSO-P0-1", "DMSO-P0-2", "DMSO-P0-3", "TPG-P0-1", "TPG-P0-2", "TPG-P0-3",
                    "DMSO-L10a-1", "DMSO-L10a-2", "DMSO-L10a-3", "TPG-L10a-1", "TPG-L10a-2", "TPG-L10a-3"]

In [28]:
allreads = pd.read_csv("../slamdunk/csv/allreads.csv", index_col=["Chromosome", "Name"]).drop(["Start", "End", "Length", "Strand"], axis=1)
tcreads = pd.read_csv("../slamdunk/csv/tcreads.csv", index_col=["Chromosome", "Name"]).drop(["Start", "End", "Length", "Strand"], axis=1)

allreads.columns = samples
tcreads.columns = samples

allreads.head()

                                       DMSO-Total-1  DMSO-Total-2  \
Chromosome Name
chr1       OR4F5|ENSG00000186092.7                0             0
           SAMD11|ENSG00000187634.13           1626          1174
           NOC2L|ENSG00000188976.11            1354          1074
           KLHL17|ENSG00000187961.15             94            45
           PLEKHN1|ENSG00000187583.11            11            10

                                       DMSO-Total-3  TPG-Total-1  TPG-Total-2  \
Chromosome Name
chr1       OR4F5|ENSG00000186092.7                0            0            0
           SAMD11|ENSG00000187634.13           1282         1792         1673
           NOC2L|ENSG00000188976.11            1091         1177         1088
           KLHL17|ENSG00000187961.15             77          125          117
           PLEKHN1|ENSG00000187583.11            13            4            0

                                       TPG-Total-3  DMSO-P0-1  DMSO-P0-2  \
Chromosome Name
chr1       OR4F5|ENSG00000186092.7               0          0          0
           SAMD11|ENSG00000187634.13          1543       2024       2362
           NOC2L|ENSG00000188976.11           1051       1146       1738
           KLHL17|ENSG00000187961.15           144         77         77
           PLEKHN1|ENSG00000187583.11            2          0          4

                                       DMSO-P0-3  TPG-P0-1  TPG-P0-2  \
Chromosome Name
chr1       OR4F5|ENSG00000186092.7             0         0         0
           SAMD11|ENSG00000187634.13        1872      2294      2083
           NOC2L|ENSG00000188976.11         1344      2452      1524
           KLHL17|ENSG00000187961.15          76        75       103
           PLEKHN1|ENSG00000187583.11          0        14         2

                                       TPG-P0-3  DMSO-L10a-1  DMSO-L10a-2  \
Chromosome Name
chr1       OR4F5|ENSG00000186092.7            0            0            0
           SAMD11|ENSG00000187634.13       1463         1742          717
           NOC2L|ENSG00000188976.11        1079         1606          726
           KLHL17|ENSG00000187961.15         90           44           65
           PLEKHN1|ENSG00000187583.11         0            3            8

                                       DMSO-L10a-3  TPG-L10a-1  TPG-L10a-2  \
Chromosome Name
chr1       OR4F5|ENSG00000186092.7               0           0           0
           SAMD11|ENSG00000187634.13          2048        1610        1285
           NOC2L|ENSG00000188976.11           1313        1440        1212
           KLHL17|ENSG00000187961.15            85         121          72
           PLEKHN1|ENSG00000187583.11            2          58          11

                                       TPG-L10a-3
Chromosome Name
chr1       OR4F5|ENSG00000186092.7              0
           SAMD11|ENSG00000187634.13         1211
           NOC2L|ENSG00000188976.11          1055
           KLHL17|ENSG00000187961.15           79
           PLEKHN1|ENSG00000187583.11           8

In [29]:
allreads = allreads.reset_index()
allreads["Gene"] = allreads["Name"] + "|" + allreads["Chromosome"]
allreads = allreads.set_index("Gene")
allreads = allreads.drop(columns=["Name", "Chromosome"])

tcreads = tcreads.reset_index()
tcreads["Gene"] = tcreads["Name"] + "|" + tcreads["Chromosome"]
tcreads = tcreads.set_index("Gene")
tcreads = tcreads.drop(columns=["Name", "Chromosome"])

In [30]:
allreads= allreads.filter(regex="Total|P0").sort_index(axis=1)
tcreads= tcreads.filter(regex="Total|P0").sort_index(axis=1)

In [31]:
allreads.head()

,DMSO-P0-1,DMSO-P0-2,DMSO-P0-3,DMSO-Total-1,DMSO-Total-2,DMSO-Total-3,TPG-P0-1,TPG-P0-2,TPG-P0-3,TPG-Total-1,TPG-Total-2,TPG-Total-3
Gene,,,,,,,,,,,,
OR4F5|ENSG00000186092.7|chr1,0,0,0,0,0,0,0,0,0,0,0,0
SAMD11|ENSG00000187634.13|chr1,2024,2362,1872,1626,1174,1282,2294,2083,1463,1792,1673,1543
NOC2L|ENSG00000188976.11|chr1,1146,1738,1344,1354,1074,1091,2452,1524,1079,1177,1088,1051
KLHL17|ENSG00000187961.15|chr1,77,77,76,94,45,77,75,103,90,125,117,144
PLEKHN1|ENSG00000187583.11|chr1,0,4,0,11,10,13,14,2,0,4,0,2

In [32]:
column_names = [ "RIBO-DMSO-1", "RIBO-DMSO-2", "RIBO-DMSO-3", "RNA-DMSO-1", "RNA-DMSO-2", "RNA-DMSO-3",
                                "RIBO-TPG-1", "RIBO-TPG-2", "RIBO-TPG-3", "RNA-TPG-1", "RNA-TPG-2", "RNA-TPG-3"]

In [33]:
allreads.columns = column_names
tcreads.columns = column_names

In [34]:
allreads.head()

,RIBO-DMSO-1,RIBO-DMSO-2,RIBO-DMSO-3,RNA-DMSO-1,RNA-DMSO-2,RNA-DMSO-3,RIBO-TPG-1,RIBO-TPG-2,RIBO-TPG-3,RNA-TPG-1,RNA-TPG-2,RNA-TPG-3
Gene,,,,,,,,,,,,
OR4F5|ENSG00000186092.7|chr1,0,0,0,0,0,0,0,0,0,0,0,0
SAMD11|ENSG00000187634.13|chr1,2024,2362,1872,1626,1174,1282,2294,2083,1463,1792,1673,1543
NOC2L|ENSG00000188976.11|chr1,1146,1738,1344,1354,1074,1091,2452,1524,1079,1177,1088,1051
KLHL17|ENSG00000187961.15|chr1,77,77,76,94,45,77,75,103,90,125,117,144
PLEKHN1|ENSG00000187583.11|chr1,0,4,0,11,10,13,14,2,0,4,0,2

In [36]:
allreads.filter(regex="RIBO", axis=1).to_csv("../rscript/deltaTE_v2/all/input_txt/P-TRAP_DMSOvsTPG_All.txt", sep="\t")
allreads.filter(regex="RNA", axis=1).to_csv("../rscript/deltaTE_v2/all/input_txt/Total_DMSOvsTPG_All.txt", sep="\t")

In [37]:
tcreads.filter(regex="RIBO", axis=1).to_csv("../rscript/deltaTE_v2/tc/input_txt/P-TRAP_DMSOvsTPG_TC.txt", sep="\t")
tcreads.filter(regex="RNA", axis=1).to_csv("../rscript/deltaTE_v2/tc/input_txt/Total_DMSOvsTPG_TC.txt", sep="\t")